name: form
description: Uma forma simples e poderosa para manipulação de formulários em flutter.
version: 0.0.5
homepage: https://github.com/EdsonOnildoJR/form

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  validators: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.17.10

flutter:
